USE [master]
GO
CREATE DATABASE [XsuntAdmin] CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'XsuntAdmin', FILENAME = N'E:\SQLServer\Databases\XsuntAdmin.mdf' , SIZE = 100000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'XsuntAdmin_log', FILENAME = N'D:\SQLServer\Logs\XsuntAdmin_log.ldf' , SIZE = 100000KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [XsuntAdmin] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [XsuntAdmin] SET ANSI_NULLS OFF
GO
ALTER DATABASE [XsuntAdmin] SET ANSI_PADDING OFF
GO
ALTER DATABASE [XsuntAdmin] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [XsuntAdmin] SET ARITHABORT OFF
GO
ALTER DATABASE [XsuntAdmin] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [XsuntAdmin] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [XsuntAdmin] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [XsuntAdmin] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [XsuntAdmin] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [XsuntAdmin] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [XsuntAdmin] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [XsuntAdmin] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [XsuntAdmin] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [XsuntAdmin] SET  DISABLE_BROKER
GO
ALTER DATABASE [XsuntAdmin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [XsuntAdmin] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [XsuntAdmin] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [XsuntAdmin] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [XsuntAdmin] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [XsuntAdmin] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [XsuntAdmin] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [XsuntAdmin] SET RECOVERY FULL
GO
ALTER DATABASE [XsuntAdmin] SET  MULTI_USER
GO
ALTER DATABASE [XsuntAdmin] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [XsuntAdmin] SET DB_CHAINING OFF
GO
ALTER DATABASE [XsuntAdmin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [XsuntAdmin] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [XsuntAdmin] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [XsuntAdmin] SET QUERY_STORE = OFF
GO
USE [XsuntAdmin]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE [XsuntAdmin] SET READ_WRITE
GO
